"""
api.py
------------------
Creates the single NinjaAPI instance and mounts all routers.

Connection map:
    ← auth.py     : `router`            mounted at /api/auth/
    ← routers.py  : categories_router   mounted at /api/categories/
                    branches_router     mounted at /api/branches/
                    products_router     mounted at /api/products/
                    cart_router         mounted at /api/cart/
                    orders_router       mounted at /api/orders/
                    loyalty_router      mounted at /api/loyalty/
    → config/urls.py : `api` imported and mounted at /api/
                       path("api/", api.urls)

Auto-generated by Ninja:
    /api/docs         -- Swagger UI
    /api/openapi.json -- OpenAPI 3.0 schema
"""

from ninja import NinjaAPI
from ninja.errors import HttpError

from guest_api.auth import router as auth_router        # ← guest_api/auth.py
from guest_api.routers import (                         # ← guest_api/routers.py
    categories_router,
    branches_router,
    products_router,
    cart_router,
    orders_router,
    loyalty_router,
)

# ---------------------------------------------------------------------------
# NinjaAPI instance
# ---------------------------------------------------------------------------
api = NinjaAPI(
    title   = "Restaurant API",
    version = "1.0.0",
    description = """
## Supermarket REST API — built with Django Ninja

### Routers
| Prefix              | Module       | Auth required |
|---------------------|--------------|---------------|
| `/api/auth/`        | auth.py      | No (register/login) |
| `/api/categories/`  | routers.py   | Read: No / Write: Admin |
| `/api/branches/`    | routers.py   | Read: No / Write: Admin |
| `/api/products/`    | routers.py   | Read: No / Write: Admin |
| `/api/cart/`        | routers.py   | Yes |
| `/api/orders/`      | routers.py   | Yes |
| `/api/loyalty/`     | routers.py   | Yes |

### Authentication
Send `Authorization: Bearer <token>` header.
Obtain a token via **POST /api/auth/login**.
    """,
    docs_url = "/docs",        # Swagger UI
)

# ---------------------------------------------------------------------------
# Mount routers
# ---------------------------------------------------------------------------
api.add_router("/auth/",       auth_router)          # ← auth.py
api.add_router("/categories/", categories_router)    # ← routers.py
api.add_router("/branches/",   branches_router)      # ← routers.py
api.add_router("/products/",   products_router)      # ← routers.py
api.add_router("/cart/",       cart_router)          # ← routers.py
api.add_router("/orders/",     orders_router)        # ← routers.py
api.add_router("/loyalty/",    loyalty_router)       # ← routers.py


# ---------------------------------------------------------------------------
# Global error handler
# ---------------------------------------------------------------------------
@api.exception_handler(HttpError)
def http_error(request, exc: HttpError):
    from django.http import JsonResponse
    return JsonResponse({"detail": str(exc)}, status=exc.status_code)