"""
api.py
------------------
Creates the single NinjaAPI instance and mounts all routers.

Connection map:
    ← auth.py     : `router`            mounted at /api/auth/
    ← routers.py  : categories_router   mounted at /api/categories/
                    branches_router     mounted at /api/branches/
                    products_router     mounted at /api/products/
                    cart_router         mounted at /api/cart/
                    orders_router       mounted at /api/orders/
                    loyalty_router      mounted at /api/loyalty/
    → config/urls.py : `api` imported and mounted at /api/
                       path("api/", api.urls)

Auto-generated by Ninja:
    /api/docs         -- Swagger UI
    /api/openapi.json -- OpenAPI 3.0 schema
"""

from uuid import UUID

from django.utils import timezone
from django.shortcuts import get_object_or_404
from ninja import NinjaAPI, Router
from ninja.errors import HttpError

from guest_api.auth import router as auth_router        # ← guest_api/auth.py
from guest_api.schemas import (
    MenuCategoryOut,
    GuestCartItemIn,
    GuestCartItemOut,
    GuestBillOut,
    GuestBillItemOut,
    GuestBillOrderOut,
    GuestOrderOut,
    GuestPaymentIn,
    MenuItemDetailOut,
    MenuItemSummaryOut,
    TableSessionOut,
)
from core.models import MenuCategory, MenuItem, Table, TableSession, Product
from core.notifications import notify_waiter
from guest_api.routers import (                         # ← guest_api/routers.py
    categories_router,
    branches_router,
    products_router,
    cart_router,
    orders_router,
    loyalty_router,
)

# ---------------------------------------------------------------------------
# NinjaAPI instance
# ---------------------------------------------------------------------------
api = NinjaAPI(
    title   = "Restaurant API",
    version = "1.0.0",
    description = """
## Restaurant API — built with Django Ninja

### Guest identity
Guest endpoints are mounted under `/api/guest/` and use the active table
session token from the QR code in the `X-Table-Session` header. They do not
use usernames, passwords, Django users, or Bearer authentication.

The legacy supermarket/user endpoints below remain outside `/api/guest/`
for compatibility with the older server-rendered application. They are not
part of the guest flow.

### Routers
| Prefix              | Module       | Auth required |
|---------------------|--------------|---------------|
| `/api/auth/`        | auth.py      | No (register/login) |
| `/api/categories/`  | routers.py   | Read: No / Write: Admin |
| `/api/branches/`    | routers.py   | Read: No / Write: Admin |
| `/api/products/`    | routers.py   | Read: No / Write: Admin |
| `/api/cart/`        | routers.py   | Yes |
| `/api/orders/`      | routers.py   | Yes |
| `/api/loyalty/`     | routers.py   | Yes |

### Legacy authentication
The compatibility endpoints under `/api/auth/`, `/api/cart/`, and
`/api/orders/` use `Authorization: Bearer <token>`. The React guest app does
not call these endpoints.
    """,
    docs_url = "/docs",        # Swagger UI
)

guest_session_router = Router(tags=["Guest sessions"])


@guest_session_router.get("/session/{qr_token}", response=TableSessionOut)
def resolve_guest_session(request, qr_token: UUID):
    """Resolve a table QR token into the active guest session identity."""
    table = get_object_or_404(Table, qr_token=qr_token)
    session = (
        TableSession.objects
        .filter(table=table, status=TableSession.Status.ACTIVE)
        .order_by("-started_at")
        .first()
    )
    if session is None:
        session = TableSession.objects.create(table=table)

    return TableSessionOut(
        session_token=str(session.session_token),
        table_id=table.id,
        table_number=str(table.number),
        table_label=f"Table {table.number}",
        status=session.status,
        started_at=session.started_at,
        ended_at=session.ended_at,
    )


@guest_session_router.get("/menu/categories", response=list[MenuCategoryOut])
def list_guest_categories(request):
    """Return the dine-in categories shown on the guest Home menu."""
    return list(MenuCategory.objects.all())


@guest_session_router.get(
    "/menu/categories/{category_id}/items",
    response=list[MenuItemSummaryOut],
)
def list_guest_category_items(request, category_id: int):
    """Return available products for one dine-in category."""
    category = get_object_or_404(MenuCategory, id=category_id)
    return [
        MenuItemSummaryOut(
            id=item.id,
            name=item.name,
            price=item.price,
            image_url=item.photo.url if item.photo else None,
            category_id=category.id,
        )
        for item in category.items.filter(is_available_now=True)
    ]


@guest_session_router.get("/menu/items/{item_id}", response=MenuItemDetailOut)
def get_guest_item(request, item_id: int):
    """Return one available dine-in product with its ingredients."""
    # Try MenuItem first; if it doesn't exist, fall back to Product so
    # legacy product pages can call this guest endpoint with a Product id.
    try:
        item = MenuItem.objects.get(id=item_id, is_available_now=True)
        ingredients = []
        for index, ingredient in enumerate(item.ingredients or [], start=1):
            if isinstance(ingredient, dict):
                ingredients.append({
                    "id": ingredient.get("id", index),
                    "name": ingredient.get("name", ""),
                    "allergen": ingredient.get("allergen", False),
                })
            else:
                ingredients.append({"id": index, "name": str(ingredient), "allergen": False})

        return MenuItemDetailOut(
            id=item.id,
            name=item.name,
            price=item.price,
            image_url=item.photo.url if item.photo else None,
            category_id=item.category_id,
            description=item.description,
            ingredients=ingredients,
        )
    except MenuItem.DoesNotExist:
        # Product fallback
        prod = Product.objects.filter(id=item_id, is_available=True).first()
        if prod is None:
            raise HttpError(404, "Not Found: No MenuItem matches the given query.")

        # Map Product -> MenuItemDetailOut shape
        desc_ings = [s.strip() for s in (prod.description or "").split(",") if s.strip()][:8]
        ingredients = [{"id": i+1, "name": name, "allergen": False} for i, name in enumerate(desc_ings)]
        return MenuItemDetailOut(
            id=prod.id,
            name=prod.name,
            price=prod.price,
            image_url=prod.image_url or None,
            category_id=getattr(prod, 'category_id', None),
            description=prod.description or "",
            ingredients=ingredients,
        )


    @guest_session_router.get("/cart", response=list[GuestCartItemOut])
    def get_guest_cart(request):
        """Return the current guest cart stored in the Django session."""
        return request.session.get(_guest_cart_key(request), [])


def _guest_cart_key(request) -> str:
    token = request.headers.get("X-Table-Session")
    if not token:
        raise HttpError(401, "A table session is required")
    if not TableSession.objects.filter(
        session_token=token, status=TableSession.Status.ACTIVE
    ).exists():
        raise HttpError(401, "The table session is invalid or expired")
    return f"guest_cart:{token}"


@guest_session_router.post("/cart/items", response=GuestCartItemOut)
def add_guest_cart_item(request, data: GuestCartItemIn):
    key = _guest_cart_key(request)
    cart = request.session.get(key, [])

    # Try MenuItem first; if not found, fall back to Product (legacy)
    item = None
    product_fallback = None
    try:
        item = MenuItem.objects.get(id=data.item_id, is_available_now=True)
    except MenuItem.DoesNotExist:
        product_fallback = Product.objects.filter(id=data.item_id, is_available=True).first()
        if product_fallback is None:
            raise HttpError(404, "Item not found")

    resolved_id = item.id if item is not None else product_fallback.id

    existing = next(
        (entry for entry in cart
         if entry["item_id"] == resolved_id
         and entry["excluded_ingredients"] == data.excluded_ingredients),
        None,
    )

    if existing:
        existing["quantity"] += 1
        result = existing
    else:
        name = item.name if item is not None else product_fallback.name
        iid = resolved_id
        result = {
            "cart_item_id": f"{iid}:{len(cart)}",
            "item_id": iid,
            "name": name,
            "quantity": 1,
            "excluded_ingredients": data.excluded_ingredients,
        }
        cart.append(result)

    request.session[key] = cart
    request.session.modified = True
    return result


@guest_session_router.post("/orders", response=GuestOrderOut)
def submit_guest_order(request):
    """Move the draft cart into a session order, retaining exclusions."""
    key = _guest_cart_key(request)
    cart = request.session.get(key, [])
    if not cart:
        raise HttpError(400, "Cart is empty")

    orders_key = f"guest_orders:{key.removeprefix('guest_cart:')}"
    orders = request.session.get(orders_key, [])
    order = {
        "id": len(orders) + 1,
        "status": "submitted",
        "placed_at": timezone.now().isoformat(),
        "items": cart,
    }
    orders.append(order)
    request.session[orders_key] = orders
    request.session[key] = []
    request.session.modified = True
    return order


@guest_session_router.get("/orders", response=list[GuestOrderOut])
def list_guest_orders(request):
    key = _guest_cart_key(request)
    orders_key = f"guest_orders:{key.removeprefix('guest_cart:')}"
    return request.session.get(orders_key, [])


@guest_session_router.get("/bill", response=GuestBillOut)
def get_guest_bill(request):
    key = _guest_cart_key(request)
    orders_key = f"guest_orders:{key.removeprefix('guest_cart:')}"
    orders = request.session.get(orders_key, [])
    total = Decimal("0")
    bill_orders = []
    for order in orders:
        bill_items = []
        for line in order["items"]:
            # First try MenuItem (dine-in menu). If not present, fall back
            # to Product (legacy catalog) to support orders created from
            # legacy product pages that reference Product IDs.
            try:
                item_obj = MenuItem.objects.get(id=line["item_id"])
                price_val = item_obj.price
                photo_url = item_obj.photo.url if item_obj.photo else ""
            except MenuItem.DoesNotExist:
                prod = Product.objects.filter(id=line["item_id"]).first()
                if prod is None:
                    raise HttpError(404, f"Ordered item not found: {line['item_id']}")
                price_val = prod.price
                photo_url = prod.image_url or ""

            subtotal = price_val * line["quantity"]
            total += subtotal
            bill_items.append(GuestBillItemOut(
                **line,
                price=price_val,
                subtotal=subtotal,
                photo_url=photo_url,
            ))
        bill_orders.append(GuestBillOrderOut(
            id=order["id"],
            status=order["status"],
            placed_at=order["placed_at"],
            items=bill_items,
        ))
    return {"total": total, "currency": "UZS", "orders": bill_orders}


@guest_session_router.post("/payment")
def request_guest_payment(request, data: GuestPaymentIn):
    """Record the guest's Card/Cash request for the active table session."""
    if data.method not in {"card", "cash"}:
        raise HttpError(400, "Payment method must be 'card' or 'cash'")
    token = request.headers.get("X-Table-Session")
    _guest_cart_key(request)
    payment_key = f"guest_payment:{token}"
    if request.session.get(payment_key, {}).get("status") == "requested":
        raise HttpError(409, "Payment has already been requested for this session")

    session = get_object_or_404(
        TableSession,
        session_token=token,
        status=TableSession.Status.ACTIVE,
    )
    request.session[payment_key] = {
        "method": data.method,
        "status": "requested",
    }
    request.session.modified = True

    waiter = session.table.assigned_waiter
    if waiter is not None:
        notify_waiter(waiter.id, "payment.requested", {
            "session_token": str(session.session_token),
            "table_number": session.table.number,
            "method": data.method,
        })

    return {"status": "requested"}

# ---------------------------------------------------------------------------
# Mount routers
# ---------------------------------------------------------------------------
api.add_router("/auth/",       auth_router)          # ← auth.py
api.add_router("/guest/",      guest_session_router)
api.add_router("/categories/", categories_router)    # ← routers.py
api.add_router("/branches/",   branches_router)      # ← routers.py
api.add_router("/products/",   products_router)      # ← routers.py
api.add_router("/cart/",       cart_router)          # ← routers.py
api.add_router("/orders/",     orders_router)        # ← routers.py
api.add_router("/loyalty/",    loyalty_router)       # ← routers.py


# ---------------------------------------------------------------------------
# Global error handler
# ---------------------------------------------------------------------------
@api.exception_handler(HttpError)
def http_error(request, exc: HttpError):
    from django.http import JsonResponse
    return JsonResponse({"detail": str(exc)}, status=exc.status_code)