# Generated by Django 6.0.7 on 2026-08-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menucategory_restaurantorder_table_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('waiter_confirmed', 'Waiter confirmed'), ('kitchen_in_progress', 'Kitchen in progress'), ('ready', 'Ready'), ('served', 'Served'), ('rejected', 'Rejected')], default='submitted', max_length=24),
        ),
    ]
