# Generated by Django 6.0.7 on 2026-08-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurantorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='assigned_cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_tickets', to='core.waiter'),
        ),
    ]
