# Generated by Django 6.0.7 on 2026-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kitchenticket_assigned_cook'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
